# Generated by Django 4.1.5 on 2023-02-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Murid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('program_studi', models.CharField(max_length=100)),
                ('harga_program', models.CharField(max_length=100)),
                ('nama', models.CharField(max_length=60)),
                ('nim', models.CharField(default='', max_length=30)),
                ('alamat', models.CharField(max_length=500)),
                ('tanggal_lahir', models.DateField()),
                ('email', models.CharField(max_length=60)),
                ('jenis_kelamin', models.CharField(max_length=20)),
                ('no_telp', models.CharField(max_length=20)),
                ('sudah_bayar', models.BooleanField()),
                ('accepted', models.BooleanField()),
                ('last_updated_by', models.CharField(default='', max_length=100)),
                ('referral_code', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('owner', models.CharField(default='', max_length=100)),
                ('created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
