# Generated by Django 4.1.5 on 2023-02-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='murid',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
