# Generated by Django 4.1.5 on 2023-02-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_murid_last_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='murid',
            name='hari_belajar',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='murid',
            name='jam_belajar',
            field=models.CharField(default='', max_length=400),
        ),
    ]
