# Generated by Django 4.1.5 on 2023-01-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Murid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_studi', models.CharField(max_length=100)),
                ('harga_program', models.CharField(max_length=100)),
                ('nama', models.CharField(max_length=60)),
                ('alamat', models.CharField(max_length=500)),
                ('tanggal_lahir', models.DateField()),
                ('email', models.CharField(max_length=60)),
                ('jenis_kelamin', models.CharField(max_length=20)),
                ('no_telp', models.CharField(max_length=20)),
                ('sudah_bayar', models.BooleanField()),
                ('accepted', models.BooleanField()),
            ],
        ),
    ]
