# Generated by Django 4.1.5 on 2023-01-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='murid',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
